//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace takip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Durumlar_Tbl
    {
        public Durumlar_Tbl()
        {
            this.Isler_Tbl = new HashSet<Isler_Tbl>();
        }
    
        public int durumID { get; set; }
        public string durumAd { get; set; }
    
        public virtual ICollection<Isler_Tbl> Isler_Tbl { get; set; }
    }
}
