//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace takip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Isler_Tbl
    {
        public int isID { get; set; }
        public string isBaslik { get; set; }
        public string isAciklama { get; set; }
        public Nullable<int> isPersonelID { get; set; }
        public Nullable<System.DateTime> iletilenTarih { get; set; }
        public Nullable<System.DateTime> yapilanTarih { get; set; }
        public Nullable<int> isDurumID { get; set; }
    
        public virtual Durumlar_Tbl Durumlar_Tbl { get; set; }
        public virtual Personel_Tbl Personel_Tbl { get; set; }
    }
}
