//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace takip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IsTakipDBEntities : DbContext
    {
        public IsTakipDBEntities()
            : base("name=IsTakipDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Birimler_Tbl> Birimler_Tbl { get; set; }
        public DbSet<Durumlar_Tbl> Durumlar_Tbl { get; set; }
        public DbSet<Isler_Tbl> Isler_Tbl { get; set; }
        public DbSet<Personel_Tbl> Personel_Tbl { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Yetki_Tbl> Yetki_Tbl { get; set; }
    }
}
