//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace takip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel_Tbl
    {
        public Personel_Tbl()
        {
            this.Isler_Tbl = new HashSet<Isler_Tbl>();
        }
    
        public int perID { get; set; }
        public string perAdSoyad { get; set; }
        public string perKullaniciAdi { get; set; }
        public string perParola { get; set; }
        public Nullable<int> perBirimID { get; set; }
        public Nullable<int> perYetkiTurID { get; set; }
    
        public virtual Birimler_Tbl Birimler_Tbl { get; set; }
        public virtual ICollection<Isler_Tbl> Isler_Tbl { get; set; }
        public virtual Yetki_Tbl Yetki_Tbl { get; set; }
    }
}
