//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace takip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetki_Tbl
    {
        public Yetki_Tbl()
        {
            this.Personel_Tbl = new HashSet<Personel_Tbl>();
        }
    
        public int YetkiTurID { get; set; }
        public string YetkiTurAd { get; set; }
    
        public virtual ICollection<Personel_Tbl> Personel_Tbl { get; set; }
    }
}
